import './globals.css';
import Navbar from '../components/navbar/navbar';
import Footer from '../components/footer/footer';
import { Inter, Poppins } from 'next/font/google';

const inter = Poppins({ subsets: ['latin'], weight: ['500', '700'] });

export const metadata = {
  title: 'nex',
  description: 'Generated by next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='container'>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
